function [headers, sacdata] = sacreada(filename)
% [headers, SACdata] = sacread('filename')
%     Read in a binary sacfile to matlab
%     and returns a structure of the sac header
%     with the array of amplitude data inclusive SAC.data
%     and a structure of the header SAC
%     data and headers are seperated
%     
%     Header fields can be accessed using 
%       SAC.fieldname of getfield(SAC, 'fieldname')
%       where fieldname is a field within the structure SAC
%       fieldname can be listed using 
%       fieldnames(headers)
%
%     Data points are accessed using all array functions
%       but the are internal to the structure
%       sacdata(1)
%       sacdata(npts-30)
%       sacdata(1:npts)
%
%     Some important fields are
%        headers.npts    - Number of data points
%        headers.dt      - Delta time between data points (seconds)
%        headers.b       - Beginning time (seconds)
%        headers.e       - Ending time (seconds)
%        headers.dist    - Distance between station and reciever (km)
%        headers.az      - Azimuth,  Event to Station Azimuth
%        headers.gcarc   - Great Circle Distance (degrees)
%        headers.baz     - Back Azimuth Station to Event Azimuth
%        headers.stlo    - Station Longitude
%        headers.stla    - Station Latitude
%        headers.evlo    - Event Longitude 
%        headers.evla    - Event Latitude
%
%     Example:
%        [headers, sacdata] = sacread('my_data.sac');
%        plot(linspace(headers.b, headers.e, headers.npts), sacdata)
%        
%     See also STRUCT, GETFIELD, SETFIELD, FIELDNAMES, LINSPACE, PLOT
if(iscell(filename) == 1) 
    filename = char(filename);
end
    
fid = fopen(filename,'r');
if(fid == -1) 
    error([ 'Error opening file: ' filename])
    return
end
fhdr = fread(fid,14*5,'float');
ihdr = fread(fid,8*5,'int');
chdr = fread(fid,24*8,'char')';
chdr = char(chdr);
npts = ihdr(10);
sacdata = fread(fid, npts,'float');
fclose(fid);

headers = struct('dt', fhdr(1), ...
      'depmin', fhdr(2), ...
      'depmax', fhdr(3), ...
      'scale', fhdr(4), ...
      'odelta', fhdr(5), ...
      'b', fhdr(6), ...
      'e', fhdr(7), ...
      'o', fhdr(8), ...
      'a', fhdr(9), ...
      'internal1', fhdr(10), ...
      't0', fhdr(11), ...
      't1', fhdr(12), ...
      't2', fhdr(13), ...
      't3', fhdr(14), ...
      't4', fhdr(15), ...
      't5', fhdr(16), ...
      't6', fhdr(17), ...
      't7', fhdr(18), ...
      't8', fhdr(19), ...
      't9', fhdr(20), ...
      'f', fhdr(21), ...
      'resp0', fhdr(22), ...
      'resp1', fhdr(23), ...
      'resp2', fhdr(24), ...
      'resp3', fhdr(25), ...
      'resp4', fhdr(26), ...
      'resp5', fhdr(27), ...
      'resp6', fhdr(28), ...
      'resp7', fhdr(29), ...
      'resp8', fhdr(30), ...
      'resp9', fhdr(31), ...
      'stla', fhdr(32), ...
      'stlo', fhdr(33), ...
      'stel', fhdr(34), ...
      'stdp', fhdr(35), ...
      'evla', fhdr(36), ...
      'evlo', fhdr(37), ...
      'evel', fhdr(38), ...
      'evdp', fhdr(39), ...
      'unused1', fhdr(40), ...
      'user0', fhdr(41), ...
      'user1', fhdr(42), ...
      'user2', fhdr(43), ...
      'user3', fhdr(44), ...
      'user4', fhdr(45), ...
      'user5', fhdr(46), ...
      'user6', fhdr(47), ...
      'user7', fhdr(48), ...
      'user8', fhdr(49), ...
      'user9', fhdr(50), ...
      'dist', fhdr(51), ...
      'az', fhdr(52), ...
      'baz', fhdr(53), ...
      'gcarc', fhdr(54), ...
      'internal2', fhdr(55), ...
      'internal3', fhdr(56), ...
      'depmen', fhdr(57), ...
      'cmpaz', fhdr(58), ...
      'cmpinc', fhdr(59), ...
      'unused2', fhdr(60), ...
      'unused3', fhdr(61), ...
      'unused4', fhdr(62), ...
      'unused5', fhdr(63), ...
      'unused6', fhdr(64), ...
      'unused7', fhdr(65), ...
      'unused8', fhdr(66), ...
      'unused9', fhdr(67), ...
      'unused10', fhdr(68), ...
      'unused11', fhdr(69), ...
      'unused12', fhdr(70), ...
      'nzyear', ihdr(1), ...
      'nzjday', ihdr(2), ...
      'nzhour', ihdr(3), ...
      'nzmin', ihdr(4), ...
      'nzsec', ihdr(5), ...
      'nzmsec', ihdr(6), ...
      'internal4', ihdr(7), ...
      'internal5', ihdr(8), ...
      'internal6', ihdr(9), ...
      'npts', ihdr(10), ...
      'internal7', ihdr(11), ...
      'internal8', ihdr(12), ...
      'unused13', ihdr(13), ...
      'unused14', ihdr(14), ...
      'unused15', ihdr(15), ...
      'iftype', ihdr(16), ...
      'idep', ihdr(17), ...
      'iztype', ihdr(18), ...
      'unused16', ihdr(19), ...
      'iinst', ihdr(20), ...
      'istreg', ihdr(21), ...
      'ievreg', ihdr(22), ...
      'ievtyp', ihdr(23), ...
      'iqual', ihdr(24), ...
      'isynth', ihdr(25), ...
      'unused17', ihdr(26), ...
      'unused18', ihdr(27), ...
      'unused19', ihdr(28), ...
      'unused20', ihdr(29), ...
      'unused21', ihdr(30), ...
      'unused22', ihdr(31), ...
      'unused23', ihdr(32), ...
      'unused24', ihdr(33), ...
      'unused25', ihdr(34), ...
      'unused26', ihdr(35), ...
      'leven', ihdr(36), ...
      'lpsol', ihdr(37), ...
      'lovrok', ihdr(38), ...
      'lcalda', ihdr(39), ...
      'unused27', ihdr(40), ...
      'kstnm', chdr(1:8), ...
      'kevnm', chdr(9:24), ...
      'khole', chdr(25:32), ...
      'ko', chdr(33:40), ...
      'ka', chdr(41:48), ...
      'kt0', chdr(49:56), ...
      'kt1', chdr(57:64), ...
      'kt2', chdr(65:72), ...
      'kt3', chdr(73:80), ...
      'kt4', chdr(81:88), ...
      'kt5', chdr(89:96), ...
      'kt6', chdr(97:104), ...
      'kt7', chdr(105:112), ...
      'kt8', chdr(113:120), ...
      'kt9', chdr(121:128), ...
      'kf', chdr(129:136), ...
      'kuser0', chdr(137:144), ...
      'kuser1', chdr(145:152), ...
      'kuser2', chdr(153:160), ...
      'kcmpnm', chdr(161:168), ...
      'knetwk', chdr(169:176), ...
      'kdatrd', chdr(177:184), ...
      'kinst', chdr(185:192));


